development:
  adapter: mysql2
  encoding: utf8
  database: baseball_history_development
  pool: 5
  username: root
  password:

test:
  adapter: mysql2
  encoding: utf8
  database: baseball_history_test
  pool: 5
  username: root
  password:

production:
  adapter: pg
  encoding: utf-8
  database: baseball_history_production
  pool: 5
  username: root
  password:
